{                                                                                                                    
    "global":
     "memo": "Nochance | MMS#6409_ICQ_TEST"
    default_chain: stride-testnet
    chains:
    gaia-testnet:
    key: wallet
    chain-id: GAIA
    rpc-addr: http://10.1.1.218:57121
    grpc-addr: http://10.1.1.218:59121
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
    stride-testnet:
    key: wallet
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://10.1.1.205:57152
    grpc-addr: http://10.1.1.205:59152
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
    cl: {}
}
